name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
    - uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: 🔧 Build Project
      run: |
        npm ci
        npm run build

    - name: Run tests
      run: npm test
