name: Create CNAME

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a CNAME file
      run: echo "halgory.com" > CNAME

    - name: Commit and push if changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add CNAME
        git commit -m "Add CNAME" -a || echo "No changes to commit"
        git push
