name: Create CNAME

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Wait
      run: sleep 45  # Waits for specified number of seconds
    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Ensure this matches the version specified in your logs
        cache: 'npm'

    - name: Create a CNAME file
      run: echo "halgory.com" > CNAME

    - name: Commit and push if changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add CNAME
        git commit -m "Add CNAME" -a || echo "No changes to commit"
        git push
