name: Build HalGORY

on:
  push:
    branches:
      - main  # Adjust this if your default branch has a different name

jobs:
  Build-HalGORY:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'  # Ensure to use the version compatible with your project

    - name: Install Dependencies
      run: |
        npm ci
        npm install

    - name: Build the site
      run: npm run build

    - name: Generate CNAME
      run: npm run generateCNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
        publish_branch: gh-pages
