name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ensure this matches the version specified in your logs
        cache: 'npm'
    
    - name: List contents of the docs directory
      run: ls -la ./docs

    
    - name: Install Dependencies
      run: npm install

    - name: Verify Node.js Version
      run: node -v

    - name: Run build script
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
