name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your default branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ensure to use the version compatible with your project

    - name: Install Dependencies
      run: npm install

    - name: Build the site
      run: npm run build  # Adjust according to your build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: 'gh-pages'
        keep_files: CNAME  # Retain the CNAME file
