name: Move Files to 'gh-pages'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: Set up Node.js (if needed)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust as necessary

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Copy specific files to gh-pages directory
      run: |
        cp ./CNAME ./gh-pages/  # Example of copying a single file
        cp -r ./ig/ ./gh-pages/ig/  # Example of copying a specific directory

    - name: Commit and push to gh-pages
      working-directory: ./gh-pages
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update specific files" || echo "No changes to commit"
        git push origin gh-pages
